Added documentation for Reporting PoC
DFE-Digital/database-of-qualified-teachers pull request #3
Opened 2022-04-25 13:21 UTC by dendle

# Documentation for Reporting PoC

Added documentation outlining the As-is architecture for reporting, and a proposed "to-be" state in line with the reporting PoC work.

2022-04-25 13:24 UTC, benilovj reviewed
@dendle this looks good, but is it worth also capturing:

* the other options that were evaluated alongside the 'to be' option?
* some reasoning as to why this option was chosen over the others?

2022-04-25 14:56 UTC, dendle commented
> 

Hi Jake, thanks for the feedback.  I've added relevant sections that should cover your points.

2022-04-25 14:58 UTC, benilovj approved these changes

2022-04-25 15:14 UTC, aje54 requested changes
I think we should add a link to the actual POC resources and source code (which is actually only something I can do being as the code is on my local machine :) ). But apart from that. Looks good

2022-04-28 09:54 UTC, aje54 commented
Will add in the poc code so we can refer to it.

2022-04-28 09:56 UTC, aje54 approved these changes

2022-04-28 09:57 UTC, merged